<?php

namespace Database\Seeders;

use App\Models\VoucherLedger;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LedgerSeeder extends Seeder
{

    CONST NAMES = [
        'Sales Revenue',
        'Sales Discount',
        'Cash (MBL)',
        'Cost Of Sales',
        'Purchase Ac',
        'Card Account -JBL(EBL)',
        'Card Account (MBL)',
        'Rini',
        'Pangti',
        'Poli (Ft -1282)',
        'dr shaila',
        'happy',
        'happy',
        'arpita',
        'arpita',
        'joya chy',
        'dr.shaila',
        'Annanya',
        'Suchita',
        'sohana guest of didi',
        'Konika',
        'tushi',
        'dr.shaila',
        'Linakshi',
        'shathi',
        'Rimi',
        'Amina',
        'Gitika',
        'Ananna',
        'Nargish',
        'shipu',
        'mukta',
        'mowly',
        'atiya admin',
        'Saila',
        'Priya',
        'joyee shawdagar',
        'rumpa',
        'rinky paul',
        'Monika',
        'nusrat',
        'Priya',
        'munmun',
        'ismat lovely',
        'sajiha+nafiha',
        'rozy',
        'shila barua',
        'Meherunnesa',
        'Samira',
        'Lynda',
        'kameniya',
        'Sharmistha',
        'Ishita',
        'Nishat',
        'tanjina',
        'fairuj',
        'Jui',
        'Reshmi',
        'Yeasmin',
        'Tapoti',
        'Anjana',
        'Moyurakshi',
        'Rupna',
        'Sraboni',
        'Labonnyo',
        'Moutushi',
        'Joyee',
        'shuptasree',
        'Taposree',
        'Purbasha',
        'urmi appi',
        'nabiha',
        'reena',
        'shetu',
        'shahan ara',
        'romana rahman 2537',
        'sanjida',
        'Trila',
        'sreyoshi',
        'shimul dey',
        'Shanta',
        'puja',
        'Mrittika',
        'Ananna',
        'mithila biswas',
        'Anamika',
        'jakia',
        'Monisha',
        'Moumita',
        'Evrana',
        'Nowshin',
        'Arpita',
        'mona',
        'Arundhati',
        'Nur e Jannat',
        'Atika',
        'EBABI',
        'Puja',
        'popy 2346',
        'piyali',
        'anisha',
        'papia',
        'trapa',
        'Santa dawanji',
        'Aditi',
        'Ankita',
        'shopnail',
        'jesmin',
        'Fatema',
        'Chameli',
        'Arpita',
        'Nandita',
        'trina chy ft 2535',
        'soniya',
        'Jerin',
        'bishakha',
        'puja chy',
        'shujata',
        'upoma majumdar',
        'Sukla',
        'sonia',
        'narmeen',
        'Sreeporna',
        'nawreen',
        'fahmida',
        'roma',
        'titly',
        'Dr. Monisha',
        'eliza',
        'Rojina',
        'nafisa',
        'Akhi',
        'poulomi',
        'shyama',
        'punom',
        'Mounota',
        'nipa',
        'SAIDA',
        'nasreen',
        'maisha',
        'flonace',
        'jisa',
        'Trisha',
        'athoi',
        'ahona',
        'atifa jannat',
        'shahin',
        'israt',
        'Debushmita',
        'farah akter',
        'israt',
        'naila',
        'Puspa',
        'kifayat 2511',
        'jebunnesa',
        'Nabonita',
        'Ankita',
        'tajbih',
        'Raina',
        'Puspo',
        'Joyeeta',
        'shumi',
        'brishty ahmed',
        'brishty ahmed',
        'hamida akter 2533',
        'falguni das',
        'Trina',
        'faria',
        'mehezabin',
        'Nahiyan',
        'naznin',
        'farhana',
        'mina',
        'irin',
        'maimuna',
        'tonoya',
        'Poly',
        'Arpita',
        'Sumita',
        'jannatul ferdows',
        'asha',
        'jannat',
        'tuktuk guest of bowmoni',
        'sabiha ratri',
        'rikta',
        'nazia',
        'nazia',
        'Priyanka',
        'turna',
        'Sumaiya',
        'shusmita',
        'sonia',
        'sonia',
        'shimu',
        'Alisa',
        'ekra',
        'Adiba',
        'pushpita',
        'lubaida',
        'hena',
        'shimu',
        'shajia',
        'Waziha',
        'tasfiya',
        'Jayasree',
        'Proma',
        'Purbasha',
        'nasrin',
        'rima',
        'afsana',
        'jarin',
        'shely',
        'humaira',
        'humaira',
        'ferdows',
        'jakia',
        'risa',
        'Lubna',
        'subaita',
        'sanjida',
        'shakhi',
        'keya',
        'sumi',
        'sanjida',
        'ferdows',
        'soma',
        'Kristina',
        'Shanta',
        'roji apu',
        'jannat',
        'sabrina',
        'nowaira',
        'Leen',
        'sheema',
        'sadia',
        'Lina',
        'Niva',
        'kritanjali',
        'ummul',
        'sorna mitro',
        'sorna mitro',
        'hira',
        'riha',
        'fahiya',
        'jui',
        'Agniva',
        'Rima',
        'mashuka',
        'humaira',
        'papiya chy',
        'Turin',
        'samira',
        'Ratree',
        'nipa',
        'Sonia',
        'sunonda',
        'Taifa',
        'Nuzhat',
        'mahi',
        'masfika',
        'shivani',
        'heera',
        'nasrin ahmed ankhi',
        'Fabiha',
        'messi',
        'hridita',
        'tajnia sis of sinthiya apa',
        'kashfia sis of sithiya apa',
        'kashfia sis of sinthiya apu',
        'Nusrat',
        'titly',
        'shamima',
        'sadiya',
        'ismu',
        'ismu',
        'sahila',
        'Rupa',
        'rumki',
        'farhana',
        'Auroni',
        'Sunny',
        'Piku',
        'Shawshoti',
        'farzana',
        'Zariyat+naziyat',
        'Devosree',
        'munni',
        'Targini',
        'Onna',
        'shuvaccha',
        'nasrin',
        'sweety',
        'fowzia',
        'Alishba',
        'protima',
        'sheli',
        'mitu',
        'tumpa',
        'mitu',
        'tumpa',
        'Tasniya',
        'Trisha',
        'ishma',
        'Ferdosh',
        'Labiba',
        'Shoma',
        'Sthogita',
        'payel',
        'Shima',
        'Jannatul ferdosh',
        'Israt',
        'Rafiya',
        'Priyanka',
        'Sahana',
        'tista',
        'Ruma',
        'Anannya',
        'Khadiza',
        'tasrin',
        'rima mohajon',
        'oishee',
        'priosa',
        'shumi dus',
        'tasfia',
        'priya dus',
        'Prama',
        'faija',
        'Miskatul',
        'munira',
        'farhana',
        'puja',
        'shaina',
        'shahina',
        'rajeya',
        'lopa',
        'shurma',
        'abida',
        'saima hasan',
        'jachiha',
        'jobeda',
        'mowmita',
        'etu',
        'tasrin sultana',
        'nafiun nawar',
        'anuradha dhar',
        'liza dhar',
        'dipa barua',
        'sumaia',
        'rokser',
        'DIA',
        'Rokser',
        'Chandrika',
        'PUJA BARUA',
        'Swarnali',
        'joinab',
        'alfi',
        'alfi',
        'puja chy',
        'rumy',
        'priya dus',
        'kanta',
        'marjan happy',
        'Tanni',
        'champa',
        'turna',
        'Rizwana',
        'nusrat jahan',
        'israt jahan 2263',
        'sanjida',
        'ria barua',
        'rajosree barua',
        'shuchona',
        'shaila akter',
        'Nibedita',
        'Matra',
        'Tultul',
        'Kakoli',
        'Uma',
        'shetu',
        'tanni',
        'joysree',
        'ratna singa guest of shemoly jamalkhan',
        'joya dher',
        'shostika',
        'ripa da',
        'pulok',
        'Trisha',
        'isha dus gupta',
        'shornika',
        'mili',
        'rakhi devi',
        'richi',
        'moon',
        'Joyeeta',
        'arpa',
        'Kanta',
        'Puja',
        'Promi',
        'Trishum',
        'lipi',
        'Apshora',
        'shusmita',
        'Shanchita',
        'Jutika',
        'Priyonti',
        'Swarna',
        'runa',
        'dr.shurovi',
        'nusrat',
        'nuva',
        'mishu',
        'Nusrat',
        'mamun',
        'Fatema',
        'chahaat',
        'sneha',
        'Yashra+unaiza',
        'aratrika',
        'shumi',
        'shumi',
        'Papiya',
        'Joysree',
        'Anamika',
        'srijita',
        'srijita',
        'Akashlina',
        'isha dus gupta',
        'Juthi',
        'Oishee',
        'Momo',
        'Shyama',
        'Joyosree',
        'Lipi',
        'Priyanka',
        'Kouwri',
        'Arpa',
        'Ivi',
        'brishty dhar',
        'rushita',
        'Rima',
        'ananna',
        'tasrin',
        'Nafisa',
        'Dipshikha',
        'Nadiya',
        'sanjida',
        'isha dus gupta',
        'Shilpi',
        'aratrika',
        'adri',
        'Sushmita',
        'farzana',
        'rishatul',
        'Nipa',
        'shoily',
        'Payel',
        'Anamika',
        'Brishty',
        'rakhi debi',
        'Tanni',
        'fahmida',
        'nakshi',
        'nakshi',
        'Mumu',
        'Chaiti',
        'Priyanka',
        'Rowshon',
        'Mandira',
        'shubortika',
        'nipa dhar',
        'sanjida',
        'joysree',
        'urmi appi',
        'Shima',
        'Lipi',
        'aleya',
        'shormi',
        'Meri',
        'chanchala',
        'Joyeeta',
        'Liza',
        'Jui',
        'najifa',
        'trisha',
        'mouli',
        'Swarna',
        'samiha',
        'bithi',
        'Rezwan ara',
        'Rikta',
        'Shupriya',
        'Pronami',
        'Sneha',
        'Priyanka',
        'fabiha',
        'Joya',
        'Piyasha',
        'Sumi',
        'amita',
        'tanisha',
        'Athoy',
        'Jaba',
        'Riya',
        'gopa',
        'Barnali',
        'shusmita ft 2531',
        'shuchona',
        'Monira',
        'tunazzina',
        'safwana',
        'sadia',
        'adri',
        'muntahina',
        'Mithila',
        'munjrin',
        'Arpa',
        'happy',
        'phuispita',
        'esha das guptu',
        'Habiba',
        'Puja',
        'joya dhor mumu',
        'Cash-MBL(Product Sale)',
        'Card Account-MBL (UCBL)',
        'Card Account -MBL (EBL)',
        'VAT Payable',
        'Cash-JBL (Product Sale)',
        'MFS (MBL)',
        'MFS (JBL)',
        'Cash MBL (Card Sell)',
        'Test333',
        'Test 2.0',
        'Card Account-JBL(UCBL)',
        'Proprietor Account-(Madam)',
        'Mobile Bill',
        'Entertainment',
        'Delivery Expense',
        'Courier Expense',
        'Repair & Maintenance (Ac)',
        'Sales Return',
        'Other Income',
        'Purchase Return',
        'Opening',
        'Transportation In',
        'Loading Unloading Charge',
        'Packaging Cost',
        'Salary',
        'House Rent',
        'Office Supplies',
        'Internet Bill',
        'Promotional Expense',
        'Sales Commission',
        'Interest Expense',
        'Income Tax',        
    ];
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach(static::NAMES as $name){
            VoucherLedger::create(compact('name'));
        }
    }
}
